"""Static area hierarchy data. Hand-maintained.

If willhaben adds or removes a district, update this file and re-run the
live drift smoke test in `tests/test_live.py` to confirm parity.
"""

from __future__ import annotations

from typing import Final

# (state_id, state_name, ((child_id, child_name), ...))
AREAS_DATA: Final[tuple[tuple[int, str, tuple[tuple[int, str], ...]], ...]] = (
    (
        3,
        "Niederösterreich",
        (
            (305, "Amstetten"),
            (306, "Baden"),
            (307, "Bruck an der Leitha"),
            (309, "Gmünd"),
            (308, "Gänserndorf"),
            (310, "Hollabrunn"),
            (311, "Horn"),
            (312, "Korneuburg"),
            (301, "Krems an der Donau"),
            (313, "Krems Land"),
            (314, "Lilienfeld"),
            (315, "Melk"),
            (316, "Mistelbach"),
            (317, "Mödling"),
            (318, "Neunkirchen"),
            (302, "Sankt Pölten"),
            (319, "Sankt Pölten Land"),
            (320, "Scheibbs"),
            (321, "Tulln"),
            (322, "Waidhofen an der Thaya"),
            (303, "Waidhofen an der Ybbs"),
            (304, "Wiener Neustadt"),
            (323, "Wiener Neustadt Land"),
            (325, "Zwettl"),
        ),
    ),
    (
        8,
        "Vorarlberg",
        (
            (801, "Bludenz"),
            (802, "Bregenz"),
            (803, "Dornbirn"),
            (804, "Feldkirch"),
        ),
    ),
    (
        22000,
        "andere Länder",
        (
            (-122, "Bosnien und Herzegowina"),
            (-119, "Bulgarien"),
            (-137, "Deutschland"),
            (-166, "Frankreich"),
            (-22, "Griechenland"),
            (-21, "Großbritannien"),
            (-127, "Italien"),
            (-128, "Kroatien"),
            (-130, "Malta"),
            (-57, "Niederlande"),
            (-44, "Polen"),
            (-132, "Portugal"),
            (-133, "Russland"),
            (-13, "Schweiz"),
            (20784, "Serbien"),
            (-168, "Slowakei"),
            (-169, "Slowenien"),
            (-134, "Spanien"),
            (-136, "Tschechien"),
            (-53, "Türkei"),
            (-139, "Ungarn"),
            (-158, "USA"),
        ),
    ),
    (
        4,
        "Oberösterreich",
        (
            (404, "Braunau am Inn"),
            (405, "Eferding"),
            (406, "Freistadt"),
            (407, "Gmunden"),
            (408, "Grieskirchen"),
            (409, "Kirchdorf an der Krems"),
            (401, "Linz"),
            (410, "Linz Land"),
            (411, "Perg"),
            (412, "Ried im Innkreis"),
            (413, "Rohrbach"),
            (414, "Schärding"),
            (402, "Steyr"),
            (415, "Steyr-Land"),
            (416, "Urfahr-Umgebung"),
            (417, "Vöcklabruck"),
            (403, "Wels"),
            (418, "Wels-Land"),
        ),
    ),
    (
        6,
        "Steiermark",
        (
            (621, "Bruck-Mürzzuschlag"),
            (603, "Deutschlandsberg"),
            (601, "Graz"),
            (606, "Graz-Umgebung"),
            (622, "Hartberg-Fürstenfeld"),
            (610, "Leibnitz"),
            (611, "Leoben"),
            (612, "Liezen"),
            (614, "Murau"),
            (620, "Murtal"),
            (623, "Südoststeiermark"),
            (616, "Voitsberg"),
            (617, "Weiz"),
        ),
    ),
    (
        1,
        "Burgenland",
        (
            (101, "Eisenstadt"),
            (103, "Eisenstadt - Umgebung"),
            (104, "Güssing"),
            (105, "Jennersdorf"),
            (106, "Mattersburg"),
            (107, "Neusiedl am See"),
            (108, "Oberpullendorf"),
            (109, "Oberwart"),
            (102, "Rust (Stadt)"),
        ),
    ),
    (
        2,
        "Kärnten",
        (
            (210, "Feldkirchen"),
            (203, "Hermagor"),
            (201, "Klagenfurt"),
            (204, "Klagenfurt Land"),
            (205, "Sankt Veit an der Glan"),
            (206, "Spittal an der Drau"),
            (202, "Villach"),
            (207, "Villach Land"),
            (208, "Völkermarkt"),
            (209, "Wolfsberg"),
        ),
    ),
    (
        5,
        "Salzburg",
        (
            (502, "Hallein"),
            (501, "Salzburg Stadt"),
            (503, "Salzburg-Umgebung"),
            (504, "Sankt Johann im Pongau"),
            (505, "Tamsweg"),
            (506, "Zell am See"),
        ),
    ),
    (
        7,
        "Tirol",
        (
            (702, "Imst"),
            (701, "Innsbruck"),
            (703, "Innsbruck-Land"),
            (704, "Kitzbühel"),
            (705, "Kufstein"),
            (706, "Landeck"),
            (707, "Lienz"),
            (708, "Reutte"),
            (709, "Schwaz"),
        ),
    ),
    (
        900,
        "Wien",
        (
            (117223, "Wien, 01. Bezirk, Innere Stadt"),
            (117224, "Wien, 02. Bezirk, Leopoldstadt"),
            (117225, "Wien, 03. Bezirk, Landstraße"),
            (117226, "Wien, 04. Bezirk, Wieden"),
            (117227, "Wien, 05. Bezirk, Margareten"),
            (117228, "Wien, 06. Bezirk, Mariahilf"),
            (117229, "Wien, 07. Bezirk, Neubau"),
            (117230, "Wien, 08. Bezirk, Josefstadt"),
            (117231, "Wien, 09. Bezirk, Alsergrund"),
            (117232, "Wien, 10. Bezirk, Favoriten"),
            (117233, "Wien, 11. Bezirk, Simmering"),
            (117234, "Wien, 12. Bezirk, Meidling"),
            (117235, "Wien, 13. Bezirk, Hietzing"),
            (117236, "Wien, 14. Bezirk, Penzing"),
            (117237, "Wien, 15. Bezirk, Rudolfsheim-Fünfhaus"),
            (117238, "Wien, 16. Bezirk, Ottakring"),
            (117239, "Wien, 17. Bezirk, Hernals"),
            (117240, "Wien, 18. Bezirk, Währing"),
            (117241, "Wien, 19. Bezirk, Döbling"),
            (117242, "Wien, 20. Bezirk, Brigittenau"),
            (117243, "Wien, 21. Bezirk, Floridsdorf"),
            (117244, "Wien, 22. Bezirk, Donaustadt"),
            (117245, "Wien, 23. Bezirk, Liesing"),
        ),
    ),
)
